project_id = "dcbcjlzzbkjyeqqylfnl"

[functions.virtual-guide]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.confirm-payment]
verify_jwt = false

[functions.create-admin]
verify_jwt = false