// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcbcjlzzbkjyeqqylfnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjYmNqbHp6YmtqeWVxcXlsZm5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTcwNjYsImV4cCI6MjA3MTI3MzA2Nn0.Rns03ADFpUlOD-_no3kZ20d1xKh4Hsd1lyM_XolrAmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});